name: Create dependency bump PR
on:
  # allows manual triggering from https://github.com/../../actions/workflows/bump.yml
  workflow_dispatch:
  # runs weekly on Thursday at 8:00
  schedule:
    - cron: '0 8 * * 4'

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: nomeata/haskell-bounds-bump-action@main
      with:
        test: false


